version: '3.8'

services:
  avito_cmd:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: ["./avito_cmd"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"

volumes:
  pgdata: